name: OkiniBot Action

on:
  workflow_dispatch:

jobs:
  getFavs-sendFavs:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x, 15.x]
    steps:
      - uses: actions/checkout@v2
      - name: execute okinibot
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
        - run: npm ci
        - run: npm run build --if-present
        run: node ./index.js